server:
  port: 8088
ssrpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2181
  zkRoot: ssrpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
  grayRatio: 10 # 0-100

logging:
  level:
    root: error
    com.stephenshen.ssrpc: debug