server:
  port: 8081

ssrpc:
  zk:
    server: localhost:2181
    root: ssrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 300

ssregistry:
  servers: http://localhost:8484

logging:
  level:
    root: debug
    com.stephenshen.ssrpc: debug

app:
  id: app1
apollo:
  # 配置本地配置缓存目录
  cacheDir: /opt/data/
  # 指定使用哪个集群的配置
  cluster: default
  # 配置中心地址
  meta: http://http://kimmking.cn:8080
  # 是否开启 Spring 参数自动更新
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    # 是否启用 Apollo
    enabled: true
    # 设置 Namespace
    namespaces: app1
    eagerLoad:
      # 将 Apollo 加载提到初始化日志系统之前
      enabled: false