server:
  port: 8081

ssrpc:
  zk:
    server: localhost:2181
    root: ssrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 25

logging:
  level:
    root: error
    com.stephenshen.ssrpc: debug